In [1]:
import pandas as pd
import plotly as px
import matplotlib.pyplot as plt

In [30]:

df=pd.read_csv(r"C:\Users\Usuario\Downloads\proyecto mercado\proyecto-cosa\proyecto mercado\archive\Dow_Jones.csv")
df.head()

,Date,Ticker,Open,High,Low,Close,Adjusted,Returns,Volume
0,2020-01-02,DJI,28638.970703,28872.800781,28627.769531,28868.800781,28868.800781,NaN,251820000
1,2020-01-03,DJI,28553.330078,28716.310547,28500.359375,28634.880859,28634.880859,-0.008103,239590000
2,2020-01-06,DJI,28465.500000,28708.019531,28418.630859,28703.380859,28703.380859,0.002392,252760000
3,2020-01-07,DJI,28639.179688,28685.500000,28565.279297,28583.679688,28583.679688,-0.004170,258900000
4,2020-01-08,DJI,28556.140625,28866.179688,28522.509766,28745.089844,28745.089844,0.005647,291750000

In [31]:
df.columns.to_list()

['Date',
 'Ticker',
 'Open',
 'High',
 'Low',
 'Close',
 'Adjusted',
 'Returns',
 'Volume']

In [34]:
df_dow_jones=df[['Date','Open','Volume','Ticker']]

df_dow_jones.head()

         Date          Open     Volume Ticker
0  2020-01-02  28638.970703  251820000    DJI
1  2020-01-03  28553.330078  239590000    DJI
2  2020-01-06  28465.500000  252760000    DJI
3  2020-01-07  28639.179688  258900000    DJI
4  2020-01-08  28556.140625  291750000    DJI

In [36]:
df=pd.read_csv(r"C:\Users\Usuario\Downloads\proyecto mercado\proyecto-cosa\proyecto mercado\archive\NASDAQ .csv")
df.head()

,Date,Ticker,Open,High,Low,Close,Adjusted,Returns,Volume
0,2020-01-02,IXIC,9039.459961,9093.429688,9010.889648,9092.190430,9092.190430,NaN,2862700000
1,2020-01-03,IXIC,8976.429688,9065.759766,8976.429688,9020.769531,9020.769531,-0.007855,2586520000
2,2020-01-06,IXIC,8943.500000,9072.410156,8943.500000,9071.469727,9071.469727,0.005620,2810450000
3,2020-01-07,IXIC,9076.639648,9091.929688,9042.549805,9068.580078,9068.580078,-0.000319,2381740000
4,2020-01-08,IXIC,9068.030273,9168.889648,9059.379883,9129.240234,9129.240234,0.006689,2472620000

In [38]:
df_nasdaq=df[['Date','Ticker','Open','Close','Volume']]
df_nasdaq.head()

         Date Ticker         Open        Close      Volume
0  2020-01-02   IXIC  9039.459961  9092.190430  2862700000
1  2020-01-03   IXIC  8976.429688  9020.769531  2586520000
2  2020-01-06   IXIC  8943.500000  9071.469727  2810450000
3  2020-01-07   IXIC  9076.639648  9068.580078  2381740000
4  2020-01-08   IXIC  9068.030273  9129.240234  2472620000

In [39]:
df=pd.read_csv(r"C:\Users\Usuario\Downloads\proyecto mercado\proyecto-cosa\proyecto mercado\archive\Portfolio_prices.csv")
df.head()

,Date,Ticker,Open,High,Low,Close,Adjusted,Returns,Volume
0,2020-01-03,JPM,137.500000,139.229996,137.080002,138.339996,119.874138,-0.013197,10386800
1,2020-01-03,KO,54.320000,54.990002,54.090000,54.689999,46.494698,-0.005455,11354500
2,2020-01-03,LMT,404.019989,417.170013,403.000000,413.739990,359.312317,0.035981,2990100
3,2020-01-03,MS,51.220001,51.450001,50.830002,51.200001,43.273079,-0.016142,6706000
4,2020-01-03,MSCI,262.200012,263.579987,259.269989,260.750000,248.019470,-0.019921,459700

In [40]:
df_pp=df[['Date','Ticker','Open','Close','Volume']]
df_pp.head()

         Date Ticker        Open       Close    Volume
0  2020-01-03    JPM  137.500000  138.339996  10386800
1  2020-01-03     KO   54.320000   54.689999  11354500
2  2020-01-03    LMT  404.019989  413.739990   2990100
3  2020-01-03     MS   51.220001   51.200001   6706000
4  2020-01-03   MSCI  262.200012  260.750000    459700

In [42]:
df_porto=pd.read_csv(r"C:\Users\Usuario\Downloads\proyecto mercado\proyecto-cosa\proyecto mercado\archive\Portfolio.csv")
df_porto.head()

  Ticker  Quantity                Sector       Close    Weight
0   AAPL         1                    IT  218.270004  3.461290
1   ADAP         1       Pharmaceuticals    0.291000  0.004615
2   AGCO         1           Agriculture   93.089996  1.476206
3     BA         2  Military Engineering  178.110001  2.824439
4     BG         4           Agriculture   73.250000  1.161586

In [43]:
df=pd.read_csv(r"C:\Users\Usuario\Downloads\proyecto mercado\proyecto-cosa\proyecto mercado\archive\SP500.csv")
df.head()

,Date,Ticker,Open,High,Low,Close,Adjusted,Returns,Volume
0,2020-01-02,GSPC,3244.669922,3258.139893,3235.530029,3257.850098,3257.850098,NaN,3459930000
1,2020-01-03,GSPC,3226.360107,3246.149902,3222.340088,3234.850098,3234.850098,-0.007060,3484700000
2,2020-01-06,GSPC,3217.550049,3246.840088,3214.639893,3246.280029,3246.280029,0.003533,3702460000
3,2020-01-07,GSPC,3241.860107,3244.909912,3232.429932,3237.179932,3237.179932,-0.002803,3435910000
4,2020-01-08,GSPC,3238.590088,3267.070068,3236.669922,3253.050049,3253.050049,0.004902,3726840000

In [44]:
df_sp500=df[['Date','Ticker','Open','Close','Volume']]
df_sp500.head()

         Date Ticker         Open        Close      Volume
0  2020-01-02   GSPC  3244.669922  3257.850098  3459930000
1  2020-01-03   GSPC  3226.360107  3234.850098  3484700000
2  2020-01-06   GSPC  3217.550049  3246.280029  3702460000
3  2020-01-07   GSPC  3241.860107  3237.179932  3435910000
4  2020-01-08   GSPC  3238.590088  3253.050049  3726840000